import { jsPDF } from "jspdf";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface TestLLCData {
  companyName: string;
  designator: string;
  ein: string;
  state: string;
  ownerFullName: string;
  ownerEmail: string;
  ownerPhone: string;
  ownerIdNumber: string;
  ownerIdType: string;
  ownerAddress: string;
  ownerCity: string;
  ownerCountry: string;
  ownerProvince: string;
  ownerPostalCode: string;
  llcCreatedDate: string;
}

interface FormData {
  memberAddress: string;
  memberPhone: string;
  capitalContribution: string;
  effectiveDate: string;
}

const testLLC: TestLLCData = {
  companyName: "ACME DIGITAL SERVICES",
  designator: "LLC",
  ein: "88-1234567",
  state: "New Mexico",
  ownerFullName: "Juan García López",
  ownerEmail: "juan.garcia@ejemplo.com",
  ownerPhone: "+34 612 345 678",
  ownerIdNumber: "12345678A",
  ownerIdType: "DNI",
  ownerAddress: "Calle Gran Vía 123, 4º Izquierda",
  ownerCity: "Madrid",
  ownerCountry: "España",
  ownerProvince: "Madrid",
  ownerPostalCode: "28013",
  llcCreatedDate: "2026-01-15",
};

const testFormData: FormData = {
  memberAddress: "Calle Gran Vía 123, 4º Izquierda, Madrid, Madrid, España 28013",
  memberPhone: "+34 612 345 678",
  capitalContribution: "10,000",
  effectiveDate: "2026-02-03",
};

function formatDate(dateStr: string): string {
  const date = new Date(dateStr);
  return date.toLocaleDateString("es-ES", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });
}

function generateOperatingAgreementPDF(llc: TestLLCData, formData: FormData): Buffer {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 25;
  const contentWidth = pageWidth - margin * 2;

  const accentColor: [number, number, number] = [110, 220, 138];
  const darkColor: [number, number, number] = [14, 18, 21];
  const grayColor: [number, number, number] = [107, 114, 128];
  const lightGray: [number, number, number] = [229, 231, 235];

  const companyFullName = `${llc.companyName} ${llc.designator}`;

  let pageNumber = 1;

  const addPageFooter = () => {
    doc.setFillColor(248, 250, 252);
    doc.rect(0, pageHeight - 20, pageWidth, 20, "F");

    doc.setFontSize(8);
    doc.setTextColor(grayColor[0], grayColor[1], grayColor[2]);
    doc.text("Operating Agreement - Generated by Easy US LLC", margin, pageHeight - 10);
    doc.text(`Page ${pageNumber}`, pageWidth - margin, pageHeight - 10, { align: "right" });
  };

  const addPageHeader = () => {
    doc.setFillColor(accentColor[0], accentColor[1], accentColor[2]);
    doc.rect(0, 0, pageWidth, 4, "F");

    doc.setFontSize(8);
    doc.setTextColor(grayColor[0], grayColor[1], grayColor[2]);
    doc.text(companyFullName, margin, 12);
    doc.text("OPERATING AGREEMENT", pageWidth - margin, 12, { align: "right" });

    doc.setDrawColor(lightGray[0], lightGray[1], lightGray[2]);
    doc.setLineWidth(0.3);
    doc.line(margin, 16, pageWidth - margin, 16);
  };

  let yPos = 0;

  const checkNewPage = (requiredSpace: number): number => {
    if (yPos + requiredSpace > pageHeight - 30) {
      addPageFooter();
      doc.addPage();
      pageNumber++;
      addPageHeader();
      return 25;
    }
    return yPos;
  };

  // ===== COVER PAGE =====
  doc.setFillColor(accentColor[0], accentColor[1], accentColor[2]);
  doc.rect(0, 0, pageWidth, 8, "F");

  doc.setFillColor(248, 250, 252);
  doc.roundedRect(pageWidth / 2 - 30, 35, 60, 20, 3, 3, "F");
  doc.setFontSize(10);
  doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
  doc.setFont("helvetica", "bold");
  doc.text("Easy US LLC", pageWidth / 2, 47, { align: "center" });

  yPos = 80;

  doc.setTextColor(darkColor[0], darkColor[1], darkColor[2]);
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.text("OPERATING AGREEMENT", pageWidth / 2, yPos, { align: "center" });

  yPos += 12;
  doc.setFontSize(14);
  doc.setTextColor(grayColor[0], grayColor[1], grayColor[2]);
  doc.text("of", pageWidth / 2, yPos, { align: "center" });

  yPos += 16;
  doc.setFontSize(22);
  doc.setTextColor(darkColor[0], darkColor[1], darkColor[2]);
  doc.setFont("helvetica", "bold");
  doc.text(companyFullName, pageWidth / 2, yPos, { align: "center" });

  yPos += 25;
  doc.setDrawColor(accentColor[0], accentColor[1], accentColor[2]);
  doc.setLineWidth(2);
  doc.line(pageWidth / 2 - 40, yPos, pageWidth / 2 + 40, yPos);

  yPos += 25;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(grayColor[0], grayColor[1], grayColor[2]);
  const introText = `This Operating Agreement governs the operations and management of ${companyFullName}, a Limited Liability Company organized under the laws of the State of ${llc.state}.`;
  const introLines = doc.splitTextToSize(introText, contentWidth - 40);
  doc.text(introLines, pageWidth / 2, yPos, { align: "center" });

  yPos += introLines.length * 6 + 20;

  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin + 20, yPos, contentWidth - 40, 30, 4, 4, "F");

  doc.setFontSize(10);
  doc.setTextColor(grayColor[0], grayColor[1], grayColor[2]);
  doc.text("Effective Date:", pageWidth / 2, yPos + 12, { align: "center" });

  doc.setFontSize(14);
  doc.setTextColor(darkColor[0], darkColor[1], darkColor[2]);
  doc.setFont("helvetica", "bold");
  doc.text(formatDate(formData.effectiveDate), pageWidth / 2, yPos + 24, { align: "center" });

  addPageFooter();

  // ===== CONTENT PAGES =====
  doc.addPage();
  pageNumber++;
  addPageHeader();
  yPos = 25;

  const addSectionTitle = (num: number, title: string) => {
    yPos = checkNewPage(20);

    doc.setFillColor(accentColor[0], accentColor[1], accentColor[2]);
    doc.roundedRect(margin, yPos, 8, 8, 1, 1, "F");

    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.text(String(num), margin + 4, yPos + 5.5, { align: "center" });

    doc.setFontSize(13);
    doc.setTextColor(darkColor[0], darkColor[1], darkColor[2]);
    doc.text(title, margin + 12, yPos + 6);

    yPos += 14;
  };

  const addParagraph = (text: string, indent: boolean = false) => {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(grayColor[0], grayColor[1], grayColor[2]);

    const xStart = indent ? margin + 8 : margin;
    const width = indent ? contentWidth - 8 : contentWidth;
    const lines = doc.splitTextToSize(text, width);

    yPos = checkNewPage(lines.length * 5 + 5);
    doc.text(lines, xStart, yPos);
    yPos += lines.length * 5 + 6;
  };

  const addLabelValue = (label: string, value: string) => {
    yPos = checkNewPage(12);

    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(grayColor[0], grayColor[1], grayColor[2]);
    doc.text(label, margin + 8, yPos);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(darkColor[0], darkColor[1], darkColor[2]);
    doc.text(value, margin + 8 + doc.getTextWidth(label) + 3, yPos);

    yPos += 6;
  };

  // SECTION 1: FORMATION
  addSectionTitle(1, "FORMATION OF THE COMPANY");
  addParagraph(
    `${companyFullName} (the "Company") is a Limited Liability Company formed under the laws of the State of ${llc.state}. The Company was formed on ${formatDate(llc.llcCreatedDate)}.`,
    true
  );
  addLabelValue("EIN: ", llc.ein);
  addLabelValue("State of Formation: ", llc.state);

  // SECTION 2: NAME AND ADDRESS
  addSectionTitle(2, "NAME AND PRINCIPAL PLACE OF BUSINESS");
  addParagraph(
    `The name of the Company is ${companyFullName}. The principal place of business shall be located at such place as the Members may determine from time to time.`,
    true
  );

  // SECTION 3: PURPOSE
  addSectionTitle(3, "PURPOSE");
  addParagraph(
    "The purpose of the Company is to engage in any lawful business activity for which a Limited Liability Company may be organized under the laws of the State of " +
      llc.state +
      ", including but not limited to consulting services, digital services, e-commerce, and related activities.",
    true
  );

  // SECTION 4: MEMBERS
  addSectionTitle(4, "MEMBERS AND MEMBERSHIP INTERESTS");
  addParagraph("The initial Member(s) of the Company and their respective ownership interests are as follows:", true);
  yPos += 5;

  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin + 8, yPos, contentWidth - 16, 35, 3, 3, "F");

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(darkColor[0], darkColor[1], darkColor[2]);
  doc.text(llc.ownerFullName, margin + 15, yPos + 12);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(grayColor[0], grayColor[1], grayColor[2]);
  doc.text(`${llc.ownerIdType}: ${llc.ownerIdNumber}`, margin + 15, yPos + 22);
  doc.text(`Ownership: 100%`, margin + 15, yPos + 30);

  yPos += 45;

  // SECTION 5: CAPITAL CONTRIBUTIONS
  addSectionTitle(5, "CAPITAL CONTRIBUTIONS");
  addParagraph(
    `The initial capital contribution to the Company is $${formData.capitalContribution} USD. Additional capital contributions may be made as agreed upon by the Members.`,
    true
  );

  // SECTION 6: MANAGEMENT
  addSectionTitle(6, "MANAGEMENT");
  addParagraph(
    "The Company shall be managed by its Members. Each Member shall have the authority to bind the Company in the ordinary course of business. Major decisions affecting the Company shall require the consent of Members holding a majority of the membership interests.",
    true
  );

  // SECTION 7: DISTRIBUTIONS
  addSectionTitle(7, "DISTRIBUTIONS");
  addParagraph(
    "Distributions of available cash or other assets shall be made to the Members in proportion to their respective membership interests, at such times and in such amounts as determined by the Members.",
    true
  );

  // SECTION 8: TAXATION
  addSectionTitle(8, "TAX ELECTIONS");
  addParagraph(
    "For U.S. federal income tax purposes, the Company shall be classified as a disregarded entity (if single-member) or partnership (if multi-member), unless the Members elect otherwise. As a non-resident owned LLC, the Company is subject to specific IRS reporting requirements.",
    true
  );

  // SECTION 9: RECORDS
  addSectionTitle(9, "BOOKS AND RECORDS");
  addParagraph(
    "The Company shall maintain complete and accurate books of account and records of all Company transactions at its principal place of business. All Members shall have the right to inspect and copy such records during normal business hours.",
    true
  );

  // SECTION 10: AMENDMENTS
  addSectionTitle(10, "AMENDMENTS");
  addParagraph(
    "This Operating Agreement may be amended only by a written instrument signed by all Members. Any amendment shall be effective as of the date specified therein or, if no date is specified, as of the date of execution.",
    true
  );

  // SECTION 11: DISSOLUTION
  addSectionTitle(11, "DISSOLUTION");
  addParagraph(
    "The Company shall be dissolved upon the occurrence of any of the following events: (a) the written consent of all Members; (b) the entry of a decree of judicial dissolution; or (c) any other event causing dissolution under applicable law.",
    true
  );

  // SECTION 12: GOVERNING LAW
  addSectionTitle(12, "GOVERNING LAW");
  addParagraph(
    `This Operating Agreement shall be governed by and construed in accordance with the laws of the State of ${llc.state}, without regard to its conflicts of law principles.`,
    true
  );

  // SIGNATURE PAGE
  doc.addPage();
  pageNumber++;
  addPageHeader();
  yPos = 40;

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(darkColor[0], darkColor[1], darkColor[2]);
  doc.text("SIGNATURES", pageWidth / 2, yPos, { align: "center" });

  yPos += 20;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(grayColor[0], grayColor[1], grayColor[2]);
  doc.text(
    "IN WITNESS WHEREOF, the undersigned has executed this Operating Agreement as of the Effective Date.",
    margin,
    yPos
  );

  yPos += 40;

  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin, yPos, contentWidth, 80, 5, 5, "F");

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(darkColor[0], darkColor[1], darkColor[2]);
  doc.text("MEMBER:", margin + 10, yPos + 15);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.text(llc.ownerFullName, margin + 10, yPos + 30);

  doc.setFontSize(9);
  doc.setTextColor(grayColor[0], grayColor[1], grayColor[2]);
  doc.text(`${llc.ownerIdType}: ${llc.ownerIdNumber}`, margin + 10, yPos + 40);
  doc.text(`Address: ${formData.memberAddress}`, margin + 10, yPos + 50);
  doc.text(`Phone: ${formData.memberPhone}`, margin + 10, yPos + 60);
  doc.text(`Email: ${llc.ownerEmail}`, margin + 10, yPos + 70);

  yPos += 100;
  doc.setDrawColor(grayColor[0], grayColor[1], grayColor[2]);
  doc.setLineWidth(0.5);
  doc.line(margin, yPos, margin + 100, yPos);

  doc.setFontSize(9);
  doc.setTextColor(grayColor[0], grayColor[1], grayColor[2]);
  doc.text("Signature", margin, yPos + 10);

  doc.line(pageWidth - margin - 80, yPos, pageWidth - margin, yPos);
  doc.text("Date", pageWidth - margin - 80, yPos + 10);

  addPageFooter();

  return Buffer.from(doc.output("arraybuffer"));
}

async function main() {
  console.log("=".repeat(60));
  console.log("OPERATING AGREEMENT GENERATOR - TEST");
  console.log("=".repeat(60));
  console.log();

  console.log("Test Data:");
  console.log("-".repeat(40));
  console.log(`Company Name: ${testLLC.companyName} ${testLLC.designator}`);
  console.log(`EIN: ${testLLC.ein}`);
  console.log(`State: ${testLLC.state}`);
  console.log(`Owner: ${testLLC.ownerFullName}`);
  console.log(`Email: ${testLLC.ownerEmail}`);
  console.log(`Phone: ${testLLC.ownerPhone}`);
  console.log(`ID: ${testLLC.ownerIdType} ${testLLC.ownerIdNumber}`);
  console.log(`Address: ${testFormData.memberAddress}`);
  console.log(`Capital Contribution: $${testFormData.capitalContribution} USD`);
  console.log(`Effective Date: ${formatDate(testFormData.effectiveDate)}`);
  console.log();

  console.log("Generating Operating Agreement PDF...");

  try {
    const pdfBuffer = generateOperatingAgreementPDF(testLLC, testFormData);

    const outputPath = path.join(__dirname, "operating-agreement-test.pdf");
    fs.writeFileSync(outputPath, pdfBuffer);

    console.log(`✓ PDF generated successfully!`);
    console.log(`  File: ${outputPath}`);
    console.log(`  Size: ${(pdfBuffer.length / 1024).toFixed(2)} KB`);
    console.log();

    console.log("=".repeat(60));
    console.log("TEST COMPLETED SUCCESSFULLY");
    console.log("=".repeat(60));
  } catch (error) {
    console.error("✗ Error generating PDF:", error);
    process.exit(1);
  }
}

main();
